apiVersion: v1
kind: Service
metadata:
  name: orderers-ca-service-nodeport
  labels: {
    component: orderers,
    type: ca
  }
spec:
  type: NodePort
  selector:
    component: orderers
    type: ca
  ports:
    - name: http
      nodePort: 31054
      protocol: TCP
      port: 7054
      targetPort: 7054
---
apiVersion: v1
kind: Service
metadata:
  name: ibm-ca-service-nodeport
  labels: {
    component: ibm,
    type: ca
  }
spec:
  type: NodePort
  selector:
    component: ibm
    type: ca
  ports:
    - name: http
      nodePort: 31055
      protocol: TCP
      port: 7054
      targetPort: 7054
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-ca-service-nodeport
  labels: {
    component: oracle,
    type: ca
  }
spec:
  type: NodePort
  selector:
    component: oracle
    type: ca
  ports:
    - name: http
      nodePort: 31056
      protocol: TCP
      port: 7054
      targetPort: 7054
---
apiVersion: v1
kind: Service
metadata:
  name: orderer0-service-nodeport
  labels: {
    component: orderer0,
    type: orderer
  }
spec:
  type: NodePort
  selector:
    component: orderer0
    type: orderer
  ports:
    - name: http
      nodePort: 31060
      protocol: TCP
      port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: orderer1-service-nodeport
  labels: {
    component: orderer1,
    type: orderer
  }
spec:
  type: NodePort
  selector:
    component: orderer1
    type: orderer
  ports:
    - name: http
      nodePort: 31061
      protocol: TCP
      port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: orderer2-service-nodeport
  labels: {
    component: orderer2,
    type: orderer
  }
spec:
  type: NodePort
  selector:
    component: orderer2
    type: orderer
  ports:
    - name: http
      nodePort: 31062
      protocol: TCP
      port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-ibm-service-nodeport
  labels: {
    component: peer0,
    type: peer,
    org: ibm
  }
spec:
  type: NodePort
  selector:
    component: peer0
    type: peer
    org: ibm
  ports:
    - name: http
      nodePort: 31070
      protocol: TCP
      port: 7051
      targetPort: 7051
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-ibm-service-nodeport
  labels: {
    component: peer1,
    type: peer,
    org: ibm
  }
spec:
  type: NodePort
  selector:
    component: peer1
    type: peer
    org: ibm
  ports:
    - name: http
      nodePort: 31071
      protocol: TCP
      port: 7051
      targetPort: 7051
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-oracle-service-nodeport
  labels: {
    component: peer0,
    type: peer,
    org: oracle
  }
spec:
  type: NodePort
  selector:
    component: peer0
    type: peer
    org: oracle
  ports:
    - name: http
      nodePort: 31072
      protocol: TCP
      port: 7051
      targetPort: 7051
---
apiVersion: v1
kind: Service
metadata:
  name: peer1-oracle-service-nodeport
  labels: {
    component: peer1,
    type: peer,
    org: oracle
  }
spec:
  type: NodePort
  selector:
    component: peer1
    type: peer
    org: oracle
  ports:
    - name: http
      nodePort: 31073
      protocol: TCP
      port: 7051
      targetPort: 7051
