apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer0-deployment
  labels: {
    component: orderer0,
    type: orderer
  }
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer0
      type: orderer
  template:
    metadata:
      labels:
        component: orderer0
        type: orderer
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: orderer0
          image: hyperledger/fabric-orderer:2.3.2
          workingDir: /var/hyperledger/orderer
          ports:
            - containerPort: 7050
          env:
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: "0.0.0.0"
          - name: ORDERER_GENERAL_GENESISMETHOD
            value: file
          - name: ORDERER_GENERAL_GENESISPROFILE
            value: OrdererGenesis
          - name: ORDERER_GENERAL_SYSTEMCHANNEL
            value: system-channel
          - name: ORDERER_GENERAL_GENESISFILE
            value: /var/hyperledger/orderer/data/genesis.block
          - name: ORDERER_GENERAL_LOCALMSPID
            value: orderer
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: /var/hyperledger/orderer/msp
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            value: /var/hyperledger/orderer/tls/server.key
          - name: ORDERER_GENERAL_TLS_CERTIFICATE
            value: /var/hyperledger/orderer/tls/server.crt
          - name: ORDERER_GENERAL_TLS_ROOTCAS
            value: "[/var/hyperledger/orderer/tls/ca.crt]"
          - name: ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR
            value: "1"
          - name: ORDERER_KAFKA_VERBOSE
            value: "true"
          - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
            value: /var/hyperledger/orderer/tls/server.key
          - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
            value: /var/hyperledger/orderer/tls/server.crt
          - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
            value: "[/var/hyperledger/orderer/tls/ca.crt]"
          volumeMounts:
            - mountPath: /var/hyperledger/orderer/msp
              name: my-pv-storage
              subPath: files/crypto-config/ordererOrganizations/orderer/orderers/orderer0/msp
            - mountPath: /var/hyperledger/orderer/tls
              name: my-pv-storage
              subPath: files/crypto-config/ordererOrganizations/orderer/orderers/orderer0/tls
            - mountPath: /var/hyperledger/orderer/data
              name: my-pv-storage
              subPath: files/orderer

