apiVersion: v1
kind: Service
metadata:
  name: ibm-ca-service
  labels: {
    component: ibm,
    type: ca
  }
spec:
  type: ClusterIP
  selector:
    component: ibm
    type: ca
  ports:
    - port: 7054
      targetPort: 7054
