apiVersion: v1
kind: Service
metadata:
  name: fabconnect-ibm-service
  labels: {
    component: fabconnect,
    type: api,
    org: ibm
  }
spec:
  type: ClusterIP
  selector:
    component: fabconnect
    type: api
    org: ibm
  ports:
    - port: 3000
      targetPort: 3000